//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailEtcTrx
    {
        public int DetailId { get; set; }
        public string TrxId { get; set; }
        public string Info { get; set; }
        public int Price { get; set; }
        public int TypeId { get; set; }
    
        public virtual HeaderTrx HeaderTrx { get; set; }
        public virtual Type Type { get; set; }
    }
}
