//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db : DbContext
    {
        public db()
            : base("name=db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetailEtcTrx> DetailEtcTrxes { get; set; }
        public virtual DbSet<DetailProductTrx> DetailProductTrxes { get; set; }
        public virtual DbSet<DetailStock> DetailStocks { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<HeaderTrx> HeaderTrxes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
